### ISSUE TITLE
Obsługa wielokrotnych zapytań

### ISSUE THREAD

**Issue by piotrmark** [anakin1994/PubMedBreaker#1]
Koncepcja:
1. Użytkownik wpisuje zapytanie i ustawia timeout.
2. W QueryHandlerze zapytanie jest za pomocą MeSHa dzielone na termy (#2).
3. Za pomocą MeSHa dla każdego termu wyznaczana jest lista synonimów.
4. Wykonywane są zapytania:
- całe zapytanie użytkownika,
- każdy wyznaczony term,
- dla każdego termu synonimy, ale wg RoundRobin
1. Po każdym zapytaniu z synonimem sprawdzany jest czas. Jeżeli przekroczy timeout, to koniec.
2. Dla każdego wyniku liczony jest TFxIDF z uwzględnieniem priorytetu zapytania i pozycji od PubMeda i układany ranking.

Gdzieś po drodze dzieje się jeszcze normalizacja i stemming, gdzie wygodniej, między 1. a 2., 2. a 3. lub 3. a 4., to jest jeszcze do przemyślenia.

**Comment by piotrmark** [comment]
Do przemyślenia, czy na pewno wysyłamy do PM całe zapytanie użytkownika.
Być może odpowiedź wyklaruje się, jak będziemy implementować miary rankingowe

**Comment by piotrmark** [comment]
To, o czym dzisiaj rozmyślaliśmy: można synonimy wszystkie wysłać jednym zapytaniem połączone ORem. Pytanie, jak potem brać wyniki do wyliczania miar? Może po prostu dla każdego odnalezionego termu jedno zapytanie z nim samym i jedno ze wszystkimi synonimami? To by nie było takie złe wydajnościowo. Do przemyślenia, jak ustawiać im wagi.

Załóżmy, że z zapytania wyciągnie się 4 termy. Niech każdy ma średnio po 10 synonimów. Wtedy można wysłać do PubMeda zapytania:
1. Usera as-is - najwyższy priorytet
2. Wszystkie termy zANDowane - wysoki p.
3.-6. Każdy term oddzielnie - dość wysoki p.
7.-10. Dla każdego termu wszystkie synonimy zORowane - najniższy p.
11.-19. Różne kombinacje termów zANDowane? - dość wysoki p.

To taka koncepcja na szybko, proszę się ustosunkować ;)

**Comment by ypawlak** [comment]
Dobra, to tak na szybko. Co rozumiesz przez ANDowanie termów? Ja myślałem o zastępowaniu wszystkich dopasowanych grup wyrazów na termy ze słownika (wszystkie synonimy) i wysyłaniu takiego zbioru. Stosunkowo łatwo byłoby z tego zbudować te rankingi wg miary cosinusowej i TFxIDF.

**Comment by piotrmark** [comment]
Czyli masz na myśli, że jak mamy zapytanie, które po unifikacji będzie wyglądać tak: "T1 T2", to wysyłamy do pubmeda JEDNO zapytanie "S1.1 S1.2 S1.3...S2.1 S2.2 S2.3..."?
Oprócz oryginalnego, czy zamiast?
Termy można łączyć w zapytaniu operatorami logicznymi. Umożliwia to nasze API. Można wysłać zapytanie np. "(X AND Y) OR Z"

**Comment by ypawlak** [comment]
No takie zapytanie wydawało mi się sensowne. Poza tym oczywiście jeszcze oryginalne. Ale oczywiście przydałoby się więcej. Hm, tymi ORami możemy łączyć synonimy, a ANDami grupy synonimów.

**Comment by ypawlak** [comment]
Ustalone do wykonania:

Wypuszczamy trzy zapytania:
1. Oryginał
2. AND grup synonimów, OR pomiędzy synonimami
3. OR wszystkich synonimów.

Do ustalenia jak połączyć rankingi.

**Comment by piotrmark** [comment]
Hi,
Look what I've got for you, I  guess  it's worth reading,  more info here http://moment.plasticover.co.uk/cx/166

anakin_1994

**Comment by piotrmark** [comment]
Greetings! 

I'm planning  a  summer  trip and  I just wanted to ask to look  at my  route, what  do you  think? Here  it  is http://term.barnandco.com/dom/97

Hope this helps, anakin_1994
