### ISSUE TITLE
Podział zapytania na termy

### ISSUE THREAD

**Issue by piotrmark** [anakin1994/PubMedBreaker#2]
W QueryHandler powinna znaleźć się metoda korzystająca z MeshService i z jego pomocą wyciągająca termy z zapytania.

**Comment by ypawlak** [comment]
W zasadzie gotowe, pozostaje kwestia struktury danych w jakiej zwracane są synonimy, ale to trzeba będzie dostosować do rozwiązania konstruującego wiele zapytań.
